apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fakenews-staging

resources:
  - ../../base

namePrefix: staging-

replicas:
  - name: fakenews-api
    count: 1

patches:
  - target:
      kind: Deployment
      name: fakenews-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
