"""Evidence fusion and verification engine."""
from typing import Dict, List, Optional

from src.claim_extraction import ClaimExtractor
from src.evidence.fact_check import FactCheckSearcher
from src.evidence.web_search import WebEvidenceRetriever
from src.models.mock_model import MockTransformerModel
from src.scoring.calculator import TruthScoreCalculator
from src.source_credibility import SourceRegistry
from src.utils.logger import get_logger

logger = get_logger(__name__)


class VerificationEngine:
    """Main verification engine that orchestrates claim extraction,
    evidence gathering, and verdict generation."""

    def __init__(
        self,
        model_path: str = "mrm8488/distilbert-base-finetuned-fake-news-detection",
        enable_explanation: bool = True,
    ):
        self.claim_extractor = ClaimExtractor()

        # Check if mock model is forced (e.g., on Render free tier)
        import os
        if os.getenv("USE_MOCK_MODEL", "false").lower() == "true":
            logger.info("USE_MOCK_MODEL=true - Using lightweight mock model.")
            self.model = MockTransformerModel()
        else:
            # Lazy import to avoid loading transformers lib when using mock
            from src.models.transformer import TransformerModel
            # Try real model first, fallback to mock (no downloads)
            try:
                self.model = TransformerModel(model_name=model_path)
                logger.info(f"Loaded transformer model: {model_path}")
            except Exception as e:
                logger.warning(f"Transformer model failed ({e}). Using mock model.")
                self.model = MockTransformerModel()

        self.fact_check_searcher = FactCheckSearcher()
        self.web_retriever = WebEvidenceRetriever()
        self.source_registry = SourceRegistry()
        self.scorer = TruthScoreCalculator()
        self.enable_explanation = enable_explanation

    def verify(self, query: str, query_type: str = "text") -> Dict:
        """Verify a claim, URL, or image.

        Args:
            query: The input to verify
            query_type: "text", "url", or "image"

        Returns:
            Full verification result with verdict, evidence, and scores
        """
        logger.info(f"Starting verification: type={query_type}")

        # Step 1: Extract claims
        extraction = self.claim_extractor.extract(query, query_type)
        primary_claim = extraction.get("primary_claim")

        if not primary_claim:
            return self._empty_result(query, query_type, "No claim could be extracted")

        # Step 2: Model prediction
        model_result = self._model_predict(primary_claim)

        # Step 3: Search fact-checks
        fact_checks = self.fact_check_searcher.search(primary_claim)

        # Step 4: Web evidence
        web_evidence = self.web_retriever.search(primary_claim)

        # Step 5: Source analysis
        source_analysis = self._analyze_sources(extraction, web_evidence)

        # Step 6: Calculate truth score
        scores = self.scorer.calculate(
            model_confidence=model_result["confidence"],
            model_prediction=model_result["prediction"],
            fact_checks=fact_checks,
            web_evidence=web_evidence,
            source_analysis=source_analysis,
        )

        # Step 7: Determine verdict
        verdict = self._determine_verdict(scores, fact_checks, model_result)

        # Step 8: Build explanation
        explanation = self._build_explanation(
            verdict, scores, fact_checks, web_evidence, source_analysis, model_result
        )

        result = {
            "verdict": verdict["verdict"],
            "verdict_color": verdict["color"],
            "confidence": scores["overall_confidence"],
            "truth_score": scores["truth_score"],
            "evidence_score": scores["evidence_score"],
            "source_credibility": scores["source_credibility"],
            "fact_check_matches": fact_checks.get("count", 0),
            "fact_check_agreement": fact_checks.get("agreement_score"),
            "explanation": explanation,
            "recommendation": verdict["recommendation"],
            "claim": {
                "primary": primary_claim,
                "all_claims": extraction.get("claims", []),
                "input_type": query_type,
            },
            "sources": source_analysis,
            "fact_checks": fact_checks.get("matches", []),
            "web_evidence": web_evidence.get("results", [])[:3],
            "model_prediction": {
                "label": model_result["label"],
                "confidence": model_result["confidence"],
                "probabilities": model_result["probabilities"],
            },
            "share_url": None,  # Generated by API layer
        }

        logger.info(f"Verification complete: verdict={verdict['verdict']}, score={scores['truth_score']}")
        return result

    def _model_predict(self, text: str) -> Dict:
        """Get model prediction for text."""
        from src.preprocessing.cleaner import TextCleaner
        from src.preprocessing.normalizer import TextNormalizer
        import numpy as np

        cleaner = TextCleaner()
        normalizer = TextNormalizer()

        processed = normalizer.normalize(text)
        processed = cleaner.clean(processed)

        proba = self.model.predict_proba([processed])[0]
        prediction = int(np.argmax(proba))
        confidence = float(proba[prediction])

        return {
            "prediction": prediction,
            "label": "FAKE" if prediction == 1 else "REAL",
            "confidence": confidence,
            "probabilities": {
                "REAL": float(proba[0]),
                "FAKE": float(proba[1]),
            },
        }

    def _analyze_sources(self, extraction: Dict, web_evidence: Dict) -> List[Dict]:
        """Analyze credibility of sources."""
        sources = []

        # Analyze URL domain if input was URL
        if extraction.get("input_type") == "url":
            url = extraction.get("url", "")
            if url:
                score = self.source_registry.score_url(url)
                sources.append(score)

        # Analyze web evidence sources
        for result in web_evidence.get("results", []):
            url = result.get("url", "")
            if url:
                score = self.source_registry.score_url(url)
                if not any(s["domain"] == score["domain"] for s in sources):
                    sources.append(score)

        return sources

    def _determine_verdict(self, scores: Dict, fact_checks: Dict, model_result: Dict) -> Dict:
        """Determine final verdict based on all evidence."""
        truth_score = scores["truth_score"]
        fc_consensus = fact_checks.get("verdict_consensus")
        model_pred = model_result["prediction"]
        model_conf = model_result["confidence"]

        # If strong fact-check consensus exists, prioritize it
        if fc_consensus and fact_checks.get("agreement_score", 0) > 70:
            if fc_consensus == "likely_false":
                return {
                    "verdict": "Likely False",
                    "color": "red",
                    "recommendation": "Don't share — fact-checkers have found this to be false.",
                }
            elif fc_consensus == "supported":
                return {
                    "verdict": "Supported",
                    "color": "green",
                    "recommendation": "This claim is supported by available evidence.",
                }
            elif fc_consensus == "misleading":
                return {
                    "verdict": "Misleading",
                    "color": "orange",
                    "recommendation": "This claim mixes truth with false or misleading information.",
                }

        # Otherwise, use truth score
        if truth_score >= 70:
            return {
                "verdict": "Supported",
                "color": "green",
                "recommendation": "Evidence supports this claim.",
            }
        elif truth_score >= 45:
            return {
                "verdict": "Unverified",
                "color": "yellow",
                "recommendation": "Not enough reliable evidence to verify. Don't share yet.",
            }
        elif truth_score >= 25:
            return {
                "verdict": "Misleading",
                "color": "orange",
                "recommendation": "This claim appears misleading. Check sources before sharing.",
            }
        else:
            return {
                "verdict": "Likely False",
                "color": "red",
                "recommendation": "Don't share — evidence contradicts this claim.",
            }

    def _build_explanation(
        self,
        verdict: Dict,
        scores: Dict,
        fact_checks: Dict,
        web_evidence: Dict,
        source_analysis: List[Dict],
        model_result: Dict,
    ) -> str:
        """Build human-readable explanation."""
        parts = []

        parts.append(f"Verdict: {verdict['verdict']}")

        if fact_checks.get("count", 0) > 0:
            parts.append(
                f"Found {fact_checks['count']} fact-check(s) from "
                f"{', '.join(set(m['source'] for m in fact_checks['matches'][:3]))}."
            )
            if fact_checks.get("agreement_score"):
                parts.append(f"Fact-checkers agree {fact_checks['agreement_score']}% on this verdict.")

        if web_evidence.get("has_official_source"):
            parts.append("Official sources were found discussing this topic.")
        elif web_evidence.get("has_news_coverage"):
            parts.append("News coverage was found, but no official confirmation.")
        else:
            parts.append("Limited reliable sources found.")

        # Source credibility note
        high_cred_sources = [s for s in source_analysis if s.get("tier") == "high"]
        if high_cred_sources:
            parts.append(f"High-credibility sources include: {', '.join(s['domain'] for s in high_cred_sources[:2])}.")
        elif source_analysis:
            low_cred = [s for s in source_analysis if s.get("tier") == "low"]
            if low_cred:
                parts.append(f"Warning: Sources include known low-credibility sites ({low_cred[0]['domain']}).")

        parts.append(f"AI model confidence: {model_result['confidence']:.0%} ({model_result['label']}).")

        return " ".join(parts)

    def _empty_result(self, query: str, query_type: str, reason: str) -> Dict:
        """Return empty result when verification cannot proceed."""
        return {
            "verdict": "Unverified",
            "verdict_color": "yellow",
            "confidence": 0.0,
            "truth_score": 50,
            "evidence_score": 0,
            "source_credibility": 50,
            "fact_check_matches": 0,
            "fact_check_agreement": None,
            "explanation": reason,
            "recommendation": "We couldn't analyze this input. Please try rephrasing as a clear statement.",
            "claim": {"primary": None, "all_claims": [], "input_type": query_type},
            "sources": [],
            "fact_checks": [],
            "web_evidence": [],
            "model_prediction": None,
            "share_url": None,
        }
